name: Build and Deploy the project to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23
      
      - name: Install Node Dependencies
        run: npm install
      
      - name: Build Vue.js files via Vite.js
        run: npm run build
      
      - name: Upload build files to GitHub
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist
  
  deploy:
    needs: build

    permissions:
      pages: write
      id-token: write
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    runs-on: ubuntu-latest

    steps:
      - name: Deploy build files to GitHub Pages
        uses: actions/deploy-pages@v4